# Generated by Django 5.0.1 on 2024-01-02 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='topic',
        ),
        migrations.AddField(
            model_name='forum',
            name='choice',
            field=models.CharField(choices=[('Diet', 'Diet'), ('Exercise', 'Exercise')], default=1, max_length=100),
        ),
    ]
