# Generated by Django 5.0.1 on 2024-01-02 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0003_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(choices=[('Diet', 'Diet'), ('Exercise', 'Exercise')], default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='forum',
            name='choice',
            field=models.CharField(default=1, max_length=200),
        ),
    ]
