# Generated by Django 5.0.1 on 2024-01-04 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0008_remove_forum_user_forum_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='email',
        ),
    ]
