# Generated by Django 5.0.1 on 2024-01-04 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0010_discussion_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forum',
            old_name='choice',
            new_name='title',
        ),
    ]
