# Generated by Django 5.0 on 2024-01-09 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0011_rename_choice_forum_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end_time',
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(choices=[('Diet', 'Diet'), ('Exercise', 'Exercise'), ('Period', 'Period')], default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='forum',
            name='description',
            field=models.CharField(blank=True, max_length=1000000),
        ),
    ]
